### ISSUE TITLE
Allow primitive values for subscriptions

### ISSUE THREAD

**Issue by liron00** [nyura123/mobx-firebase-store#2]
https://github.com/nyura123/mobx-firebase-store/blob/master/src/index.js#L17

Based on this `merge` call, looks like there's no support for a subscription that evaluates to a primitive value.

**Comment by liron00** [comment]
E.g. I can subscribe to `/dinosaur/123` and get back `{kind: 't-rex'}`, but I can't subscribe directly to `/dinosaur/123/kind`.

**Comment by nyura123** [comment]
@liron00 that is a good point! One thing I don't like is having to use mobx.map to store firebase data. Unless I'm wrong, I think that's the only way you can observe new keys being added to an object. This forces the component to do things like dinosaur.get('kind') to extract values.

Since the component already has to know about the format of the data, then I could simply store the primitive value in fbStore under the subKey, and the client would need to do something like

const sub = {
  subKey: 'dinosaur_kind_123',
  asValue: true,
  path: 'https://.../dinosaur/123/kind'
}

const unsub = mobxStore.subscribeSubs([sub])

//observable value
const kind = mobxStore.fbStore.get('dinosaur_kind_123') 

//or could add a new method for this to MobxFirebaseStore
const kind = mobxStore.getValueForSubKey('dinosaur_kind_123')
